refactor: WonMoney 를 Money 로 변경
wootecam-gugucon/shopping-mall pull request #47
Opened 2023-08-18 08:57 UTC by rimrim990

## 🔗 관련 이슈

#32 

## 🔔 주요 사항

- WonMoney 클래스를 Money 클래스로 이름 변경
- Money 값이 음수인지 검증 로직 추가

## 🤔 의논 사항 또는 질문

- 굳 ~

2023-08-18 09:00 UTC, gunner6603 approved these changes

2023-08-18 09:06 UTC, dongjoo0-0 approved these changes

2023-08-18 09:08 UTC, dahyen0o requested changes
👍👍

2023-08-18 09:08 UTC, dahyen0o commented on src/main/java/com/gugucon/shopping/common/exception/GlobalControllerAdvice.java
> +        System.out.println(errorCode.getStatus());
나중에 로그로 넣읍시다!!

2023-08-18 09:08 UTC, dahyen0o commented on src/test/java/com/gugucon/shopping/common/domain/vo/MoneyTest.java
> +        assertThat(exception).isInstanceOf(ShoppingException.class);
에러 메세지까지 검증해주세요

2023-08-18 09:08 UTC, dahyen0o commented on src/test/java/com/gugucon/shopping/common/domain/vo/MoneyTest.java
> +class MoneyTest {
생성 성공 테스트도 추가해주세요

2023-08-19 06:24 UTC, rimrim990 commented on src/main/java/com/gugucon/shopping/common/exception/GlobalControllerAdvice.java
> +        System.out.println(errorCode.getStatus());
아 이거 안 지웠네.. 넵 일단은 print 지울게요

2023-08-19 06:32 UTC, rimrim990 commented on src/test/java/com/gugucon/shopping/common/domain/vo/MoneyTest.java
> +        assertThat(exception).isInstanceOf(ShoppingException.class);
추가했습니다 ~

2023-08-19 11:07 UTC, dahyen0o approved these changes

2023-08-19 11:10 UTC, merged