36 cd 자동화
wootecam-gugucon/shopping-mall pull request #79
Opened 2023-08-21 12:07 UTC by gunner6603

## 🔗 관련 이슈

#이슈번호

## 🔔 주요 사항

- 내용

## 🤔 의논 사항 또는 질문

- 내용

2023-08-21 15:28 UTC, dahyen0o requested changes
1. 아침 스크럼 때 설명해주시면 좋을거 같아요
2. 주석보니까 아직 수정 전인거죠..?!

2023-08-22 01:41 UTC, dahyen0o approved these changes
good job

2023-08-22 01:44 UTC, dongjoo0-0 approved these changes

2023-08-22 01:56 UTC, rimrim990 approved these changes
💃

2023-08-22 02:04 UTC, merged